mode: agentic # The mode to use, can be 'baseline', 'robust', or 'agentic'. See the paper for details.

# paths, relative to root_folder
path_test_cases: data/general_tasks/injection/test_cases.json # Path to the test cases you want to run
path_save_results: results/general_tasks_test # Path to save the results

# model settings
models: ["codellama/CodeLlama-7b-Instruct-hf"] # models to use
max_new_tokens: 1024 # maximum number of new tokens to generate
temperature: 0.7 # Temperature for sampling

# task settings
test_cases_filtered: [] # If you want to use only a subset of the test cases, specify them here
parse: True # If True, the model will be prompted to re-generate the code until it is parsable
compile: False # If False, the code will not be tested for compilation
num_compilation_attempts: 15 # If compile is True, the number of attempts to compile the code